import { parseBoard } from './engine'

export const LEVELS_PER_CHAPTER = 5
export const chapters = [
  { name: '看见杀网', description: '先观察退路，再寻找致胜一着。' },
  { name: '拆掉防线', description: '看清彼此的保护，找到防线的缺口。' },
  { name: '舍子争先', description: '权衡眼前的得失，把握转瞬即逝的先手。' },
  { name: '静着藏锋', description: '落子无声，胜机藏在下一步。' },
  { name: '攻守一线', description: '照顾自己的后方，也把握进攻的时机。' },
  { name: '综合终局', description: '看清每一条岔路，走到终局之门。' },
]

// Curated from https://github.com/dffge552/xiangqi-pwa-offline (MIT).
// Original puzzle labels are retained in sourcePuzzle; license: public/licenses/xiangqi-puzzles.txt.
// Move limits are the shortest forced wins verified against every legal black reply.
export const levels = [
  {
    id: 'chapter-1-puzzle-1-v2',
    name: '门前一步',
    theme: '马炮配合',
    moves: 2,
    tip: '先用马控制九宫，再观察炮能否借士完成最后一击。',
    fen: '3aka3/9/9/5N2C/9/9/4c2n1/4B4/4A4/3AK4',
    sourcePuzzle: '马后炮杀 01 - 基本杀法',
  },
  {
    id: 'chapter-1-puzzle-2-v2',
    name: '狭路相逢',
    theme: '双车封锁',
    moves: 3,
    tip: '两车轮流压缩黑将的活动范围，注意每次将军后的退路。',
    fen: '3a1k3/4a4/6R2/8R/2r6/9/9/1r7/4A4/3K1A3',
    sourcePuzzle: '基本杀法 21。双车错（2）. - 基本杀法',
  },
  {
    id: 'chapter-1-puzzle-3-v2',
    name: '隔岸回声',
    theme: '三子接力',
    moves: 3,
    tip: '先让一门炮牵制黑将，再让车与另一门炮接续攻势。',
    fen: '4ka3/9/5a3/4p4/6C2/9/9/7RC/2r1p4/3K5',
    sourcePuzzle: '双炮马类(17) - 残局攻杀谱',
  },
  {
    id: 'chapter-1-puzzle-4-v2',
    name: '咫尺天涯',
    theme: '马炮织网',
    moves: 3,
    tip: '马不只是进攻子，也是炮架；跳马时同时观察炮线。',
    fen: '2Ck1a3/4a4/9/5N3/9/9/5r3/3CB4/4p4/3K2B2',
    sourcePuzzle: '双炮马类(09) - 残局攻杀谱',
  },
  {
    id: 'chapter-1-puzzle-5-v2',
    name: '第一重门',
    theme: '兵马车协同',
    moves: 4,
    tip: '兵吃士之后可能被吃回，关键是马和车能否接力形成杀网。',
    fen: '3aka3/5P3/4b4/r3N4/9/8R/9/2n6/9/4KA3',
    sourcePuzzle: '钓鱼马杀 01 - 基本杀法',
  },
  {
    id: 'chapter-2-puzzle-1-v2',
    name: '宫门有隙',
    theme: '引离守卫',
    moves: 4,
    tip: '一马将军，另一马拆掉守卫；不要只计算眼前的得子。',
    fen: '3a1k3/1N2a4/9/6N2/4R4/9/9/9/3p1r3/4K4',
    sourcePuzzle: '车双马类(11) - 残局攻杀谱',
  },
  {
    id: 'chapter-2-puzzle-2-v2',
    name: '一子之重',
    theme: '炮车破象',
    moves: 4,
    tip: '调炮迫使黑象离开，再用车占领象原来守护的位置。',
    fen: '2b1k1c2/9/4b4/1C7/2p6/4R4/9/r4A3/5p3/3AK4',
    sourcePuzzle: '车炮类(01) - 残局攻杀谱',
  },
  {
    id: 'chapter-2-puzzle-3-v2',
    name: '寸步之间',
    theme: '弃兵开路',
    moves: 4,
    tip: '让兵先冲开宫门，车炮要保持连续进攻。',
    fen: '3a2b2/C2Pak3/4br3/9/9/3R5/9/4B4/4p4/2BK5',
    sourcePuzzle: '车炮兵类(03) - 残局攻杀谱',
  },
  {
    id: 'chapter-2-puzzle-4-v2',
    name: '无处借力',
    theme: '炮架转换',
    moves: 5,
    tip: '炮的进退会改变士的位置，最后让车与兵共同封锁退路。',
    fen: '4k1b2/4aP3/3a5/9/R1C6/9/9/9/4r1p2/5K3',
    sourcePuzzle: '车炮兵类(07) - 残局攻杀谱',
  },
  {
    id: 'chapter-2-puzzle-5-v2',
    name: '第二重门',
    theme: '车马炮合攻',
    moves: 5,
    tip: '车、炮轮流牵动黑士，等待马切入九宫的时机。',
    fen: '4kab2/4a4/8n/1R3N3/9/9/9/9/4r1p2/2C2K3',
    sourcePuzzle: '车马炮类(26) - 残局攻杀谱',
  },
  {
    id: 'chapter-3-puzzle-1-v2',
    name: '一卒探门',
    theme: '弃兵引士',
    moves: 4,
    tip: '兵进底线未必为了存活；观察黑士被引走后留下的空位。',
    fen: '2b1k4/4aP3/4b4/7N1/9/5R3/9/9/2r1p4/5K3',
    sourcePuzzle: '车马兵类(06) - 残局攻杀谱',
  },
  {
    id: 'chapter-3-puzzle-2-v2',
    name: '暗门初开',
    theme: '弃马破士',
    moves: 4,
    tip: '先用马迫使黑士离位，再让车炮沿着打开的通道进攻。',
    fen: '2bak4/4a4/r3b3c/1C5N1/9/9/9/3R5/4p4/3K5',
    sourcePuzzle: '车马炮类(60) - 残局攻杀谱',
  },
  {
    id: 'chapter-3-puzzle-3-v2',
    name: '宫墙回响',
    theme: '弃炮引离',
    moves: 4,
    tip: '炮与兵可以先后吸引守子，车要抓住九宫防线变化的瞬间。',
    fen: '2bak4/4aP3/4b4/9/6n2/2R3B2/9/9/5p1r1/2C1K4',
    sourcePuzzle: '车炮兵类(25) - 残局攻杀谱',
  },
  {
    id: 'chapter-3-puzzle-4-v2',
    name: '重子轻落',
    theme: '弃车引将',
    moves: 5,
    tip: '舍车把黑将引出原位，另一车与炮才能连成杀网。',
    fen: '2bak4/1R2a4/c3b4/1C7/9/3R5/9/4B4/2r1p4/3K5',
    sourcePuzzle: '双车炮类(15) - 残局攻杀谱',
  },
  {
    id: 'chapter-3-puzzle-5-v2',
    name: '第三重门',
    theme: '连续弃子',
    moves: 4,
    tip: '连续弃车也可能成立；算清马炮的最后落点，再决定取舍。',
    fen: '3N1a3/3k5/4R4/1n7/R8/9/9/9/5rn2/C2AKABc1',
    sourcePuzzle: '双车马炮类(08) - 残局攻杀谱',
  },
  {
    id: 'chapter-4-puzzle-1-v2',
    name: '回身有路',
    theme: '调车伏杀',
    moves: 3,
    tip: '第一步未必要将军。把车调到能够同时照顾攻守的纵线。',
    fen: '5a3/9/3kb4/2N6/9/6C2/7R1/1n1p5/4p4/5K3',
    sourcePuzzle: '车马炮类(01) - 残局攻杀谱',
  },
  {
    id: 'chapter-4-puzzle-2-v2',
    name: '无声落子',
    theme: '帅马困毙',
    moves: 4,
    tip: '帅的进退会改变黑将的合法落点，留意不用将军的困毙。',
    fen: '4k4/4N4/9/9/9/9/9/9/4K4/9',
    sourcePuzzle: '单马类(13) - 残局攻杀谱',
  },
  {
    id: 'chapter-4-puzzle-3-v2',
    name: '两岸相望',
    theme: '移相开路',
    moves: 4,
    tip: '先移开挡路的相，让车得到通道；同时提防黑车的反击。',
    fen: '5k3/9/9/9/9/7r1/4R4/4B4/9/4K1B2',
    sourcePuzzle: '白脸将杀 01 - 基本杀法',
  },
  {
    id: 'chapter-4-puzzle-4-v2',
    name: '帐前一步',
    theme: '退炮藏锋',
    moves: 4,
    tip: '炮吃卒后还可以后退，最后一步可能需要仕来调整炮架。',
    fen: '5a3/5k3/5a3/9/9/6C2/9/4KA3/5p3/9',
    sourcePuzzle: '单炮类(02) - 残局攻杀谱',
  },
  {
    id: 'chapter-4-puzzle-5-v2',
    name: '第四重门',
    theme: '单马控宫',
    moves: 6,
    tip: '马要先绕路限制黑将，再消灭边卒；帅也能参与最后封锁。',
    fen: '3k5/9/9/p8/9/9/9/1N7/9/4K4',
    sourcePuzzle: '单马类(17) - 残局攻杀谱',
  },
  {
    id: 'chapter-5-puzzle-1-v2',
    name: '后院微火',
    theme: '运帅避锋',
    moves: 4,
    tip: '黑卒已逼近九宫，先运帅避开威胁，再寻找兵的致胜时机。',
    fen: '4ka3/3P1P3/4b4/9/9/9/9/9/3p2p2/4K4',
    sourcePuzzle: '二鬼拍门 01 - 基本杀法',
  },
  {
    id: 'chapter-5-puzzle-2-v2',
    name: '分秒之间',
    theme: '马兵应变',
    moves: 4,
    tip: '马兵进攻时别忘了身后的黑卒，必要时用帅应对将军。',
    fen: '3N2b2/9/3k5/4P4/2b5n/9/9/9/3p5/4K4',
    sourcePuzzle: '马兵类(03) - 残局攻杀谱',
  },
  {
    id: 'chapter-5-puzzle-3-v2',
    name: '轻装前行',
    theme: '先手除患',
    moves: 5,
    tip: '马的将军可以带出吃车机会，消除后患后再用兵破士。',
    fen: '3ak4/4a2r1/4P4/9/4Nc2R/7n1/9/2n6/5p3/2B1K1B2',
    sourcePuzzle: '车马兵类(09) - 残局攻杀谱',
  },
  {
    id: 'chapter-5-puzzle-4-v2',
    name: '将中有将',
    theme: '攻中有守',
    moves: 6,
    tip: '连将之后需要调车照顾底线。黑炮的反击也要算在计划内。',
    fen: '2r2a3/3N1k3/5a3/9/9/4R4/3p5/9/4A3c/3K1A3',
    sourcePuzzle: '车马类(13) - 残局攻杀谱',
  },
  {
    id: 'chapter-5-puzzle-5-v2',
    name: '第五重门',
    theme: '连将解围',
    moves: 7,
    tip: '己方九宫受压时，车马必须用连续将军保持先手。',
    fen: '4ka3/9/5a3/2R1p4/6N2/9/9/3A5/3r1p3/4KAB1c',
    sourcePuzzle: '车马类(09) - 残局攻杀谱',
  },
  {
    id: 'chapter-6-puzzle-1-v2',
    name: '岔路尽头',
    theme: '多路应对',
    moves: 6,
    tip: '从炮的调位开始，同时计算黑将移动与黑士遮挡的不同分支。',
    fen: '5a3/3k2N2/bR3a3/7C1/9/9/4p4/5K3/2r6/3n5',
    sourcePuzzle: '车马炮类(27) - 残局攻杀谱',
  },
  {
    id: 'chapter-6-puzzle-2-v2',
    name: '曲径回廊',
    theme: '弃车长攻',
    moves: 7,
    tip: '弃车之后仍要连续组织攻势，让马与另一车接力完成长追。',
    fen: '3ak4/4a4/4b4/9/3N3R1/9/3p5/8R/r3p4/3K5',
    sourcePuzzle: '双车马类(12) - 残局攻杀谱',
  },
  {
    id: 'chapter-6-puzzle-3-v2',
    name: '星火围城',
    theme: '炮兵借仕',
    moves: 7,
    tip: '兵可以引将，仕可以调整炮架；不要忽略后方棋子的作用。',
    fen: '4k4/5P2c/3P5/9/6b2/9/9/9/4AK1n1/3A1CB2',
    sourcePuzzle: '其它的杀着(12) - 残局攻杀谱',
  },
  {
    id: 'chapter-6-puzzle-4-v2',
    name: '万象迷途',
    theme: '双马接力',
    moves: 7,
    tip: '车先打开宫门，两马交替接力；准备应对黑将不同的退路。',
    fen: '4R4/4ak3/3Nb4/9/C2N5/9/9/9/4p4/3K2Brc',
    sourcePuzzle: '其它的杀着(14) - 残局攻杀谱',
  },
  {
    id: 'chapter-6-puzzle-5-v2',
    name: '终局之门',
    theme: '帅马终局',
    moves: 8,
    tip: '棋子虽少，控宫仍需精算。马先除象，再借帅的纵线限制黑将。',
    fen: '9/9/3kbN3/9/9/9/9/9/9/4K4',
    sourcePuzzle: '单马类(05) - 残局攻杀谱',
  },
].map((level) => ({ ...level, board: parseBoard(level.fen) }))

export type Level = (typeof levels)[number]
