import type { LaserLevel } from './engine'

export const LASER_LEVELS: readonly LaserLevel[] = [
  {
    id: 'easy-1',
    name: '第一次折射',
    difficulty: '简单',
    description: '转动一面镜子，让光束向上抵达水晶。',
    rows: 5,
    cols: 5,
    par: 1,
    emitters: [{ row: 2, col: 0, direction: 'E' }],
    mirrors: [{ row: 2, col: 4, orientation: '\\' }],
    solution: ['/'],
    crystals: [{ row: 0, col: 4 }],
  },
  {
    id: 'easy-2',
    name: '长廊尽头',
    difficulty: '简单',
    description: '光会穿过沿途水晶，再被镜面折向终点。',
    rows: 5,
    cols: 5,
    par: 1,
    emitters: [{ row: 4, col: 0, direction: 'E' }],
    mirrors: [{ row: 4, col: 4, orientation: '\\' }],
    solution: ['/'],
    crystals: [
      { row: 4, col: 2 },
      { row: 1, col: 4 },
    ],
  },
  {
    id: 'easy-3',
    name: '双折线',
    difficulty: '简单',
    description: '连续两次折射，把光送往右侧水晶。',
    rows: 5,
    cols: 5,
    par: 2,
    emitters: [{ row: 0, col: 0, direction: 'S' }],
    mirrors: [
      { row: 4, col: 0, orientation: '/' },
      { row: 4, col: 4, orientation: '\\' },
    ],
    solution: ['\\', '/'],
    crystals: [{ row: 1, col: 4 }],
    walls: [{ row: 2, col: 2 }],
  },
  {
    id: 'medium-1',
    name: '一束双星',
    difficulty: '中等',
    description: '规划一条同时经过两颗水晶的路径。',
    rows: 6,
    cols: 6,
    par: 1,
    emitters: [{ row: 3, col: 0, direction: 'E' }],
    mirrors: [{ row: 3, col: 5, orientation: '\\' }],
    solution: ['/'],
    crystals: [
      { row: 3, col: 2 },
      { row: 0, col: 5 },
    ],
    walls: [{ row: 1, col: 3 }],
  },
  {
    id: 'medium-2',
    name: '逆光回转',
    difficulty: '中等',
    description: '用两面镜子让光束折返到上层通道。',
    rows: 6,
    cols: 6,
    par: 2,
    emitters: [{ row: 5, col: 0, direction: 'E' }],
    mirrors: [
      { row: 5, col: 5, orientation: '\\' },
      { row: 0, col: 5, orientation: '\\' },
    ],
    solution: ['/', '\\'],
    crystals: [
      { row: 2, col: 5 },
      { row: 0, col: 2 },
    ],
    walls: [{ row: 3, col: 2 }],
  },
  {
    id: 'medium-3',
    name: '遮蔽航线',
    difficulty: '中等',
    description: '避开墙体，完成一条三段式光路。',
    rows: 6,
    cols: 6,
    par: 2,
    emitters: [{ row: 5, col: 0, direction: 'E' }],
    mirrors: [
      { row: 5, col: 4, orientation: '\\' },
      { row: 1, col: 4, orientation: '/' },
    ],
    solution: ['/', '\\'],
    crystals: [
      { row: 5, col: 2 },
      { row: 3, col: 4 },
      { row: 1, col: 1 },
    ],
    walls: [
      { row: 2, col: 2 },
      { row: 4, col: 5 },
    ],
  },
  {
    id: 'hard-1',
    name: '棱镜初鸣',
    difficulty: '复杂',
    description: '分束器把光分为直行与顺时针转向两束。',
    rows: 7,
    cols: 7,
    par: 1,
    emitters: [{ row: 6, col: 0, direction: 'E' }],
    mirrors: [{ row: 6, col: 3, orientation: '\\' }],
    solution: ['/'],
    splitters: [{ row: 3, col: 3 }],
    crystals: [
      { row: 0, col: 3 },
      { row: 3, col: 6 },
    ],
  },
  {
    id: 'hard-2',
    name: '分岔星图',
    difficulty: '复杂',
    description: '先送光进入棱镜，再修正分支末端。',
    rows: 7,
    cols: 7,
    par: 2,
    emitters: [{ row: 6, col: 0, direction: 'E' }],
    mirrors: [
      { row: 6, col: 2, orientation: '\\' },
      { row: 3, col: 6, orientation: '\\' },
    ],
    solution: ['/', '/'],
    splitters: [{ row: 3, col: 2 }],
    crystals: [
      { row: 0, col: 2 },
      { row: 0, col: 6 },
    ],
    walls: [{ row: 5, col: 5 }],
  },
  {
    id: 'hard-3',
    name: '折光回廊',
    difficulty: '复杂',
    description: '让分出的两束光分别穿越回廊，点亮终端水晶。',
    rows: 7,
    cols: 7,
    par: 3,
    emitters: [{ row: 6, col: 0, direction: 'E' }],
    mirrors: [
      { row: 6, col: 3, orientation: '\\' },
      { row: 1, col: 3, orientation: '/' },
      { row: 4, col: 6, orientation: '\\' },
    ],
    solution: ['/', '\\', '/'],
    splitters: [{ row: 4, col: 3 }],
    crystals: [
      { row: 1, col: 0 },
      { row: 0, col: 6 },
    ],
    walls: [
      { row: 2, col: 1 },
      { row: 3, col: 5 },
      { row: 5, col: 5 },
    ],
  },
]
