import type { Game } from '../types'

export const games: Game[] = [
  {
    id: 'ai-feihualing',
    name: '令 AI飞花令擂台',
    description: '围绕一个题眼与 AI 轮流对诗，AI 裁判会根据题眼、节奏、命中词库和速度评分。',
    coverImage: '/covers/ai-feihualing.svg',
    tags: ['AI', '古诗词', '对战'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'ai-poetry-guess',
    name: '画 AI诗画猜诗',
    description: '根据 AI 生成的诗意画面线索反推名句，追加提示会扣分，连击答对更高分。',
    coverImage: '/covers/ai-poetry-guess.svg',
    tags: ['AI', '古诗词', '益智'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'minesweeper',
    name: '💣 扫雷',
    description: '经典扫雷游戏，找出所有隐藏的地雷！左键揭开格子，右键标记地雷。',
    coverImage: '/covers/minesweeper.svg',
    tags: ['益智', '策略'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'snake',
    name: '🐍 贪吃蛇',
    description: '控制蛇吃掉食物，躲避自己的身体！越长越有挑战性。',
    coverImage: '/covers/snake.svg',
    tags: ['经典', '休闲'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: '24points',
    name: '🃏 24点',
    description: '使用加减乘除运算，将四个数字组合得到24！锻炼数学思维。',
    coverImage: '/covers/24points.svg',
    tags: ['益智', '数学'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: '2048',
    name: '🔢 2048',
    description: '滑动方块，合并相同数字，目标是达到2048！',
    coverImage: '/covers/2048.svg',
    tags: ['益智', '策略'],
    difficulties: ['简单', '中等'],
  },
  {
    id: 'memory',
    name: '🧠 记忆翻牌',
    description: '翻开卡片找到配对的图案，考验你的记忆力！',
    coverImage: '/covers/memory.svg',
    tags: ['益智', '记忆'],
    difficulties: ['简单', '中等'],
  },
  {
    id: 'whack-a-mole',
    name: '🔨 打地鼠',
    description: '快速点击冒出来的地鼠，争取最高分！',
    coverImage: '/covers/whackamole.svg',
    tags: ['反应', '休闲'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'slide-puzzle',
    name: '🧩 滑块拼图',
    description: '移动方块还原图片，挑战你的空间思维！',
    coverImage: '/covers/slide-puzzle.svg',
    tags: ['益智', '拼图'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'reaction-test',
    name: '⚡ 反应测试',
    description: '测试你的反应速度，看看你能多快点击！',
    coverImage: '/covers/reaction-test.svg',
    tags: ['反应', '测试'],
    difficulties: ['简单'],
  },
  {
    id: 'tic-tac-toe',
    name: '⭕ 井字棋',
    description: '经典的三连棋游戏，与AI对战！',
    coverImage: '/covers/tic-tac-toe.svg',
    tags: ['经典', '对战'],
    difficulties: ['简单', '中等'],
  },
  {
    id: 'tetris',
    name: '🧱 俄罗斯方块',
    description: '经典俄罗斯方块，堆叠方块消除行！',
    coverImage: '/covers/tetris.svg',
    tags: ['经典', '休闲'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'breakout',
    name: '🎮 打砖块',
    description: '控制挡板反弹小球，打破所有砖块！',
    coverImage: '/covers/breakout.svg',
    tags: ['经典', '休闲'],
    difficulties: ['简单', '中等', '复杂'],
  },
  {
    id: 'wordle',
    name: '🔤 Wordle',
    description: '猜单词游戏，每天一个新挑战！',
    coverImage: '/covers/wordle.svg',
    tags: ['益智', '文字'],
    difficulties: ['中等'],
  },
  {
    id: 'gomoku',
    name: '⚫ 五子棋',
    description: '经典五子棋，连成五子获胜！',
    coverImage: '/covers/gomoku.svg',
    tags: ['策略', '对战'],
    difficulties: ['简单', '中等', '复杂'],
  },
]
